// import RecordAudio2 from 'components/RecordAudio2';
import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
const RecordAudio2 = dynamic(() => import('../components/RecordAudio2'), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <div className='h-screen w-screen'>
      <Head>
        <title>WaveForm</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-5/6 m-auto mt-8'>
        {/* <RecordAudio /> */}
        <RecordAudio2 />
      </div>
    </div>
  );
};

export default Home;
