import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
const RecordAudio = dynamic(() => import('../components/RecordAudio'), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <div className='h-screen w-screen'>
      <Head>
        <title>WaveForm</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-[1040px] m-auto mt-8'>
        <RecordAudio />
      </div>
    </div>
  );
};

export default Home;
